project:
  type: website
  output-dir: docs

website:
  title: "ameyateli.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: shake.qmd
        text: "Shakespeare Text Analysis"
      - href: simstudy.qmd
        text: "Simulation Study"
      - text: "Data Viz"
        menu:
          - href: epl.qmd
            text: "Premier League 2021-2022"
          - href: londonmarathon.qmd
            text: "London Marathon"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

