---
title: "Project "
description:
  Analysis of Holiday Movie data from the Internet Movie Database 
author: Ameya Teli
date: September 28, 2024
format: html
execute: 
  warning: false
  message: false
---

[Link to Database](https://developer.imdb.com/non-commercial-datasets/)

```{r}
library(ggplot2)
tuesdata <- tidytuesdayR::tt_load('2023-12-12')

holiday_movies <- tuesdata$holiday_movies
holiday_movie_genres <- tuesdata$holiday_movie_genres

holiday_movie_genres
holiday_movies
```

First Plot - What genre do movies with love in the title fall under?

```{r}
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)

colnames(holiday_movies)
#holiday_movies$simple_title

love <- holiday_movies|>
  filter(str_detect(simple_title, "love"))
love

love_genre <- love|>
  mutate(genre_list = genres)|>
  separate(genres, c('first','second', 'third'))
love_genre

love_movies <- inner_join(love_genre, holiday_movie_genres, by = "tconst")
love_movies

ggplot(love_movies, aes(x = genres))+ geom_bar(stat = "count")+labs(title = "Genres of Holiday Movies with Love in the Title", x = "Genre")
```

This plot shows that the most prevalent genre's for holiday movies about love are Romance, Family, Drama, and Comedy.

2nd Plot - Genres of Holiday Movies

```{r}

ggplot(holiday_movie_genres, aes(x = genres)) + 
  geom_bar(stat = "count") + 
  labs(title = "Genres of Holiday Movies", x = "Genre") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

3rd Plot -
